services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=exampleuser'
      - 'POSTGRES_DB=exampledatabase'
      - 'POSTGRES_PASSWORD=secret'