INSERT INTO oauth2_client_registration (client_registration_id,
                                        client_authentication_method,
                                        client_authorization_grant_type,
                                        client_id, client_name, client_redirect_uri,
                                        client_scopes,
                                        client_secret,
                                        provider_authorization_uri,
                                        provider_configuration_metadata,
                                        provider_issuer_uri,
                                        provider_jwk_set_uri,
                                        provider_token_uri,
                                        provider_user_info_endpoint_authentication_method,
                                        provider_user_info_endpoint_uri,
                                        provider_user_info_endpoint_user_name_attribute_name)
VALUES ('desktop-client',
        'client_secret_basic',
        'authorization_code',
        'desktop-client',
        'desktop-client',
        '{baseUrl}/login/oauth2/code/{registrationId}',
        'openid,resources.read',
        'desktop-secret',
        'http://localhost:9000/oauth2/authorize',
        '{"authorization_endpoint":"http://localhost:9000/oauth2/authorize","token_endpoint":"http://localhost:9000/oauth2/token","introspection_endpoint":"http://localhost:9000/oauth2/introspect","revocation_endpoint":"http://localhost:9000/oauth2/revoke","pushed_authorization_request_endpoint":"http://localhost:9000/oauth2/par","device_authorization_endpoint":"http://localhost:9000/oauth2/device_authorization","issuer":"http://localhost:9000","jwks_uri":"http://localhost:9000/oauth2/jwks","scopes_supported":["openid"],"response_types_supported":["code"],"grant_types_supported":["authorization_code","client_credentials","refresh_token","urn:ietf:params:oauth:grant-type:device_code","urn:ietf:params:oauth:grant-type:token-exchange"],"code_challenge_methods_supported":["S256"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt","private_key_jwt","tls_client_auth","self_signed_tls_client_auth"],"introspection_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt","private_key_jwt","tls_client_auth","self_signed_tls_client_auth"],"revocation_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt","private_key_jwt","tls_client_auth","self_signed_tls_client_auth"],"request_uri_parameter_supported":true,"tls_client_certificate_bound_access_tokens":true,"dpop_signing_alg_values_supported":["RS256","RS384","RS512","PS256","PS384","PS512","ES256","ES384","ES512"],"subject_types_supported":["public"],"userinfo_endpoint":"http://localhost:9000/userinfo","end_session_endpoint":"http://localhost:9000/connect/logout","id_token_signing_alg_values_supported":["RS256"]}',
        'http://localhost:9000',
        'http://localhost:9000/oauth2/jwks',
        'http://localhost:9000/oauth2/token',
        'header',
        'http://localhost:9000/userinfo',
        'sub');
