debug: true
server:
  address: 127.0.0.1
  port: 8082

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: Web Application
  datasource:
    password: tiger
    url: jdbc:postgresql://localhost:5432/auth
    username: scott
  docker:
    compose:
      lifecycle-management: start_only
      file: ../docker-compose.yml
  security:
    oauth2:
      client:
        registration:
          web-client:
            provider: spring
            client-id: web-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - resources.read
            client-name: web-client
        provider:
          spring:
            issuer-uri: http://localhost:9000
  jpa:
    hibernate:
      ddl-auto: update

example:
  client-registration-id: web-client
  resource-server-url: "http://127.0.0.1:8090"

