debug: true
server:
  address: 127.0.0.1
  port: 8082

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: Web Application
  security:
    oauth2:
      client:
        registration:
          web-client:
            provider: spring
            client-id: web-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - resources.read
            client-name: web-client
        provider:
          spring:
            issuer-uri: http://localhost:9000
