debug: true
server:
  address: 127.0.0.1
  port: 8082

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: Web Application
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:32768/exampledatabase
    username: exampleuser
  docker:
    compose:
      lifecycle-management: start_only
      file: ../docker-compose.yml
  security:
    oauth2:
      client:
        registration:
          web-client:
            provider: spring
            client-id: web-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - resources.read
            client-name: web-client
        provider:
          spring:
            issuer-uri: http://localhost:9000
  sql:
    init:
      continue-on-error: true
      mode: always
      schema-locations:
        - classpath*:/org/springframework/security/oauth2/client/oauth2-client-schema-postgres.sql

example:
  client-registration-id: web-client
  resource-server-url: "http://127.0.0.1:8090"

