debug: true
logging:
  level:
    org.springframework.security: trace
server:
  port: 9000
spring:
  application:
    name: Authentication Server
  security:
    oauth2:
      authorizationserver:
        issuer: http://127.0.0.1:9000
        client:
          vaadin-client:
            registration:
              client-id: vaadin-client
              client-secret: "{noop}vaadin"
              client-name: Vaadin Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:8083/login/oauth2/code/vaadin-client-oidc
              scopes:
                - openid
                - profile
                - email
                - phone
                - address
              post-logout-redirect-uris:
                - http://localhost:8083
            require-authorization-consent: false
          web-client:
            registration:
              client-id: web-client
              client-secret: "{noop}secret"
              client-name: Web Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:8082/login/oauth2/code/web-client-oidc
                - http://localhost:8082/login/oauth2/code/web-client-authorization-code
              scopes:
                - openid
                - profile
                - email
                - phone
                - address
                - resources.read
              post-logout-redirect-uris:
                - http://localhost:8082
            require-authorization-consent: false
    user:
      name: admin
      password: '{noop}password'
      roles:
        - USER
        - ADMIN