INSERT INTO oauth2_registered_client (id, client_id, client_id_issued_at, client_secret, client_secret_expires_at, client_name, client_authentication_methods, authorization_grant_types, redirect_uris, post_logout_redirect_uris, scopes,
                                      client_settings, token_settings)
VALUES ('desktop-client', 'desktop-client', '2025-08-24 10:22:14.524909', '{noop}desktop-secret', null, 'Desktop Client', 'client_secret_basic', 'refresh_token,client_credentials,authorization_code',
        'http://127.0.0.1:8085/login/oauth2/code/desktop-client', '', 'address,phone,resources.read,openid,profile,offline_access,email',
        '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}',
        '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');
INSERT INTO oauth2_registered_client (id, client_id, client_id_issued_at, client_secret, client_secret_expires_at, client_name, client_authentication_methods, authorization_grant_types, redirect_uris, post_logout_redirect_uris, scopes,
                                      client_settings, token_settings)
VALUES ('hilla-client', 'hilla-client', '2025-08-24 10:22:14.539704', '{noop}hilla', null, 'Hilla Client', 'client_secret_basic', 'refresh_token,client_credentials,authorization_code', 'http://127.0.0.1:8084/login/oauth2/code/hilla-client',
        'http://127.0.0.1:8084', 'address,phone,resources.read,openid,profile,email', '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}',
        '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');
INSERT INTO oauth2_registered_client (id, client_id, client_id_issued_at, client_secret, client_secret_expires_at, client_name, client_authentication_methods, authorization_grant_types, redirect_uris, post_logout_redirect_uris, scopes,
                                      client_settings, token_settings)
VALUES ('vaadin-client', 'vaadin-client', '2025-08-24 10:22:14.541902', '{noop}vaadin', null, 'Vaadin Client', 'client_secret_basic', 'refresh_token,client_credentials,authorization_code',
        'http://127.0.0.1:8083/login/oauth2/code/vaadin-client', 'http://127.0.0.1:8083', 'address,phone,resources.read,openid,profile,email',
        '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}',
        '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');
INSERT INTO oauth2_registered_client (id, client_id, client_id_issued_at, client_secret, client_secret_expires_at, client_name, client_authentication_methods, authorization_grant_types, redirect_uris, post_logout_redirect_uris, scopes,
                                      client_settings, token_settings)
VALUES ('web-client', 'web-client', '2025-08-24 10:22:14.544491', '{noop}secret', null, 'Web Client', 'client_secret_basic', 'refresh_token,client_credentials,authorization_code', 'http://127.0.0.1:8082/login/oauth2/code/web-client',
        'http://127.0.0.1:8082', 'address,phone,resources.read,openid,profile,offline_access,email',
        '{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":false}',
        '{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');

INSERT INTO users (username, password, enabled)
VALUES ('admin', '{bcrypt}$2a$10$I6piWLkF0lmDxzBGGkP4C.CEegMOZDcKLK3jS6Pzya3xPm.ZAl5ia', 1),
       ('user', '{bcrypt}$2a$10$uS3GPw4hUR9hsbvoXPSYI.QT.zHzkvGe.lK9qRU67gYw76IkDJM12', 1);

INSERT INTO authorities (username, authority)
VALUES ('admin', 'ROLE_ADMIN'),
       ('admin', 'ROLE_USER'),
       ('user', 'ROLE_USER');
