debug: true
server:
  address: 127.0.0.1
  port: 8083

logging:
  level:
    org.springframework.security: trace
    org.atmosphere: warn

spring:
  application:
    name: Vaadin Application
  security:
    oauth2:
      client:
        registration:
          vaadin-client-oidc:
            provider: spring
            client-id: vaadin-client
            client-secret: vaadin
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
            client-name: vaadin-client-oidc
        provider:
          spring:
            issuer-uri: http://localhost:9000

  mustache:
    check-template-location: false

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,com.example.vaadin

