debug: true
server:
  port: 8084

logging:
  level:
    org.springframework.security: trace
    org.atmosphere: warn

spring:
  application:
    name: Hilla Application
  security:
    oauth2:
      client:
        registration:
          hilla-client-oidc:
            provider: spring
            client-id: hilla-client
            client-secret: hilla
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
            client-name: hilla-client-oidc
        provider:
          spring:
            issuer-uri: http://localhost:9000

  mustache:
    check-template-location: false

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.example.application

