debug: true
logging:
  level:
    com.example: debug
server:
  port: 0
spring:
  application:
    name: Desktop Application
  security:
    oauth2:
      client:
        registration:
          desktop-client:
            provider: spring
            client-id: desktop-client
            client-secret: desktop-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - resources.read
            client-name: desktop-client
        provider:
          spring:
            issuer-uri: http://localhost:9000
  threads:
    virtual:
      enabled: true